name: Build, Push & GitOps Deploy ShopEasy

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-backend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-backend:latest \
            ./backend

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-backend:latest

      - name: Build & push frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-frontend:latest \
            ./frontend

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shopeasy-frontend:latest

  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: Rike12/shopeasy-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: shopeasy-gitops

      - name: Update frontend image tag
        run: |
          cd shopeasy-gitops

          sed -i "s|image: .*shopeasy-frontend:.*|image: oluwademilade/shopeasy-frontend:${{ github.sha }}|" \
            apps/shopeasy/frontend-blue.yaml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add apps/shopeasy/frontend-blue.yaml

          git commit -m "Update frontend image to ${{ github.sha }}"

          git push origin main
